# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.4.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if getattr(globals().get("__spec__"), "parent", None) or __package__ or "." in __name__:
    from . import _lizards
else:
    import _lizards

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _lizards.delete_SwigPyIterator

    def value(self):
        return _lizards.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _lizards.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _lizards.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _lizards.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _lizards.SwigPyIterator_equal(self, x)

    def copy(self):
        return _lizards.SwigPyIterator_copy(self)

    def next(self):
        return _lizards.SwigPyIterator_next(self)

    def __next__(self):
        return _lizards.SwigPyIterator___next__(self)

    def previous(self):
        return _lizards.SwigPyIterator_previous(self)

    def advance(self, n):
        return _lizards.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _lizards.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _lizards.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _lizards.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _lizards.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _lizards.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _lizards.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _lizards:
_lizards.SwigPyIterator_swigregister(SwigPyIterator)
BAND = _lizards.BAND
PEAK = _lizards.PEAK
VOLCANO = _lizards.VOLCANO
WATER = _lizards.WATER
SCRUB = _lizards.SCRUB
PLAINS = _lizards.PLAINS
FERTILE = _lizards.FERTILE
TEMPLE = _lizards.TEMPLE
RUIN = _lizards.RUIN
SWAMP = _lizards.SWAMP
DEN = _lizards.DEN
RED_DEN = _lizards.RED_DEN
BLACK_DEN = _lizards.BLACK_DEN
GREEN_DEN = _lizards.GREEN_DEN
YELLOW_DEN = _lizards.YELLOW_DEN
GREY_DEN = _lizards.GREY_DEN
HOME_DEN = _lizards.HOME_DEN
RED = _lizards.RED
GREEN = _lizards.GREEN
GREY = _lizards.GREY
BLACK = _lizards.BLACK
YELLOW = _lizards.YELLOW
UNSETTLED = _lizards.UNSETTLED
FORMAT_FILE_TXT = _lizards.FORMAT_FILE_TXT
FORMAT_FILE_XML = _lizards.FORMAT_FILE_XML
FORMAT_FILE_JS = _lizards.FORMAT_FILE_JS
FORMAT_STRING_TXT = _lizards.FORMAT_STRING_TXT
FORMAT_STRING_XML = _lizards.FORMAT_STRING_XML
FORMAT_STRING_JS = _lizards.FORMAT_STRING_JS
NORTH = _lizards.NORTH
NORTHEAST = _lizards.NORTHEAST
SOUTHEAST = _lizards.SOUTHEAST
SOUTH = _lizards.SOUTH
SOUTHWEST = _lizards.SOUTHWEST
NORTHWEST = _lizards.NORTHWEST
DIRECTIONS = _lizards.DIRECTIONS
OWNED_ALL = _lizards.OWNED_ALL
OWNED_BAND_ONLY = _lizards.OWNED_BAND_ONLY
OWNED_SPY_ONLY = _lizards.OWNED_SPY_ONLY
OWNED_BAND_SPY = _lizards.OWNED_BAND_SPY
class point_t(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    x = property(_lizards.point_t_x_get, _lizards.point_t_x_set)
    y = property(_lizards.point_t_y_get, _lizards.point_t_y_set)

    def __init__(self, *args):
        _lizards.point_t_swiginit(self, _lizards.new_point_t(*args))

    def __eq__(self, p):
        return _lizards.point_t___eq__(self, p)

    def __ne__(self, p):
        return _lizards.point_t___ne__(self, p)

    def __iadd__(self, p):
        return _lizards.point_t___iadd__(self, p)

    def __add__(self, p):
        return _lizards.point_t___add__(self, p)

    def __sub__(self, p):
        return _lizards.point_t___sub__(self, p)

    def clip(self, arg2, arg3):
        return _lizards.point_t_clip(self, arg2, arg3)

    def tostring(self):
        return _lizards.point_t_tostring(self)

    def __str__(self):
        return _lizards.point_t___str__(self)
    __swig_destroy__ = _lizards.delete_point_t

# Register point_t in _lizards:
_lizards.point_t_swigregister(point_t)
class fpoint_t(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    x = property(_lizards.fpoint_t_x_get, _lizards.fpoint_t_x_set)
    y = property(_lizards.fpoint_t_y_get, _lizards.fpoint_t_y_set)

    def __init__(self, *args):
        _lizards.fpoint_t_swiginit(self, _lizards.new_fpoint_t(*args))
    __swig_destroy__ = _lizards.delete_fpoint_t

# Register fpoint_t in _lizards:
_lizards.fpoint_t_swigregister(fpoint_t)
class fbox_t(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    left = property(_lizards.fbox_t_left_get, _lizards.fbox_t_left_set)
    top = property(_lizards.fbox_t_top_get, _lizards.fbox_t_top_set)
    right = property(_lizards.fbox_t_right_get, _lizards.fbox_t_right_set)
    bottom = property(_lizards.fbox_t_bottom_get, _lizards.fbox_t_bottom_set)

    def tostring(self):
        return _lizards.fbox_t_tostring(self)

    def setunion(self, arg2):
        return _lizards.fbox_t_setunion(self, arg2)

    def __init__(self):
        _lizards.fbox_t_swiginit(self, _lizards.new_fbox_t())
    __swig_destroy__ = _lizards.delete_fbox_t

# Register fbox_t in _lizards:
_lizards.fbox_t_swigregister(fbox_t)
class fplace_t(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    center = property(_lizards.fplace_t_center_get, _lizards.fplace_t_center_set)
    bounds = property(_lizards.fplace_t_bounds_get, _lizards.fplace_t_bounds_set)
    hull = property(_lizards.fplace_t_hull_get, _lizards.fplace_t_hull_set)

    def __init__(self, arg2, arg3, arg4):
        _lizards.fplace_t_swiginit(self, _lizards.new_fplace_t(arg2, arg3, arg4))
    __swig_destroy__ = _lizards.delete_fplace_t

# Register fplace_t in _lizards:
_lizards.fplace_t_swigregister(fplace_t)
class feature_t(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def isa(self, *args):
        return _lizards.feature_t_isa(self, *args)

    def __init__(self):
        _lizards.feature_t_swiginit(self, _lizards.new_feature_t())
    __swig_destroy__ = _lizards.delete_feature_t

# Register feature_t in _lizards:
_lizards.feature_t_swigregister(feature_t)
class band_t(feature_t):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def set(self, arg2, arg3):
        return _lizards.band_t_set(self, arg2, arg3)

    def get(self, arg2):
        return _lizards.band_t_get(self, arg2)

    def size(self):
        return _lizards.band_t_size(self)

    def __init__(self):
        _lizards.band_t_swiginit(self, _lizards.new_band_t())
    __swig_destroy__ = _lizards.delete_band_t

# Register band_t in _lizards:
_lizards.band_t_swigregister(band_t)
class raft_t(feature_t):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    age = property(_lizards.raft_t_age_get, _lizards.raft_t_age_set)

    def __init__(self):
        _lizards.raft_t_swiginit(self, _lizards.new_raft_t())
    __swig_destroy__ = _lizards.delete_raft_t

# Register raft_t in _lizards:
_lizards.raft_t_swigregister(raft_t)
class hex_t(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    owner = property(_lizards.hex_t_owner_get, _lizards.hex_t_owner_set)
    id = property(_lizards.hex_t_id_get, _lizards.hex_t_id_set)

    def getid(self):
        return _lizards.hex_t_getid(self)

    def setid(self, arg2):
        return _lizards.hex_t_setid(self, arg2)
    xy = property(_lizards.hex_t_xy_get, _lizards.hex_t_xy_set)

    def isa(self, *args):
        return _lizards.hex_t_isa(self, *args)

    def get(self, arg2):
        return _lizards.hex_t_get(self, arg2)

    def set(self, arg2):
        return _lizards.hex_t_set(self, arg2)

    def tostring(self):
        return _lizards.hex_t_tostring(self)

    def __init__(self):
        _lizards.hex_t_swiginit(self, _lizards.new_hex_t())
    __swig_destroy__ = _lizards.delete_hex_t

# Register hex_t in _lizards:
_lizards.hex_t_swigregister(hex_t)
class water_t(hex_t):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _lizards.water_t_swiginit(self, _lizards.new_water_t())
    __swig_destroy__ = _lizards.delete_water_t

# Register water_t in _lizards:
_lizards.water_t_swigregister(water_t)
class whirlpool_t(water_t):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _lizards.whirlpool_t_swiginit(self, _lizards.new_whirlpool_t())
    __swig_destroy__ = _lizards.delete_whirlpool_t

# Register whirlpool_t in _lizards:
_lizards.whirlpool_t_swigregister(whirlpool_t)
class plains_t(hex_t):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _lizards.plains_t_swiginit(self, _lizards.new_plains_t())
    __swig_destroy__ = _lizards.delete_plains_t

# Register plains_t in _lizards:
_lizards.plains_t_swigregister(plains_t)
class fertile_t(hex_t):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _lizards.fertile_t_swiginit(self, _lizards.new_fertile_t())
    __swig_destroy__ = _lizards.delete_fertile_t

# Register fertile_t in _lizards:
_lizards.fertile_t_swigregister(fertile_t)
class ruin_t(hex_t):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _lizards.ruin_t_swiginit(self, _lizards.new_ruin_t())
    __swig_destroy__ = _lizards.delete_ruin_t

# Register ruin_t in _lizards:
_lizards.ruin_t_swigregister(ruin_t)
class swamp_t(hex_t):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _lizards.swamp_t_swiginit(self, _lizards.new_swamp_t())
    __swig_destroy__ = _lizards.delete_swamp_t

# Register swamp_t in _lizards:
_lizards.swamp_t_swigregister(swamp_t)
class temple_t(hex_t):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _lizards.temple_t_swiginit(self, _lizards.new_temple_t())
    __swig_destroy__ = _lizards.delete_temple_t

# Register temple_t in _lizards:
_lizards.temple_t_swigregister(temple_t)
class scrub_t(hex_t):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _lizards.scrub_t_swiginit(self, _lizards.new_scrub_t())
    __swig_destroy__ = _lizards.delete_scrub_t

# Register scrub_t in _lizards:
_lizards.scrub_t_swigregister(scrub_t)
class peak_t(hex_t):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _lizards.peak_t_swiginit(self, _lizards.new_peak_t())
    __swig_destroy__ = _lizards.delete_peak_t

# Register peak_t in _lizards:
_lizards.peak_t_swigregister(peak_t)
class volcano_t(peak_t):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _lizards.volcano_t_swiginit(self, _lizards.new_volcano_t())
    __swig_destroy__ = _lizards.delete_volcano_t

# Register volcano_t in _lizards:
_lizards.volcano_t_swigregister(volcano_t)
class cursed_t(hex_t):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _lizards.cursed_t_swiginit(self, _lizards.new_cursed_t())
    __swig_destroy__ = _lizards.delete_cursed_t

# Register cursed_t in _lizards:
_lizards.cursed_t_swigregister(cursed_t)
class den_t(hex_t):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    pop = property(_lizards.den_t_pop_get, _lizards.den_t_pop_set)
    home = property(_lizards.den_t_home_get, _lizards.den_t_home_set)

    def __init__(self):
        _lizards.den_t_swiginit(self, _lizards.new_den_t())
    __swig_destroy__ = _lizards.delete_den_t

# Register den_t in _lizards:
_lizards.den_t_swigregister(den_t)
class red_den_t(den_t):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _lizards.red_den_t_swiginit(self, _lizards.new_red_den_t())
    __swig_destroy__ = _lizards.delete_red_den_t

# Register red_den_t in _lizards:
_lizards.red_den_t_swigregister(red_den_t)
class black_den_t(den_t):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _lizards.black_den_t_swiginit(self, _lizards.new_black_den_t())
    __swig_destroy__ = _lizards.delete_black_den_t

# Register black_den_t in _lizards:
_lizards.black_den_t_swigregister(black_den_t)
class yellow_den_t(den_t):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _lizards.yellow_den_t_swiginit(self, _lizards.new_yellow_den_t())
    __swig_destroy__ = _lizards.delete_yellow_den_t

# Register yellow_den_t in _lizards:
_lizards.yellow_den_t_swigregister(yellow_den_t)
class green_den_t(den_t):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _lizards.green_den_t_swiginit(self, _lizards.new_green_den_t())
    __swig_destroy__ = _lizards.delete_green_den_t

# Register green_den_t in _lizards:
_lizards.green_den_t_swigregister(green_den_t)
class grey_den_t(den_t):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _lizards.grey_den_t_swiginit(self, _lizards.new_grey_den_t())
    __swig_destroy__ = _lizards.delete_grey_den_t

# Register grey_den_t in _lizards:
_lizards.grey_den_t_swigregister(grey_den_t)
class layout_t(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def realize(self):
        return _lizards.layout_t_realize(self)

    def __init__(self):
        _lizards.layout_t_swiginit(self, _lizards.new_layout_t())
    __swig_destroy__ = _lizards.delete_layout_t

# Register layout_t in _lizards:
_lizards.layout_t_swigregister(layout_t)
class vectors(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _lizards.vectors_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _lizards.vectors___nonzero__(self)

    def __bool__(self):
        return _lizards.vectors___bool__(self)

    def __len__(self):
        return _lizards.vectors___len__(self)

    def __getslice__(self, i, j):
        return _lizards.vectors___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _lizards.vectors___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _lizards.vectors___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _lizards.vectors___delitem__(self, *args)

    def __getitem__(self, *args):
        return _lizards.vectors___getitem__(self, *args)

    def __setitem__(self, *args):
        return _lizards.vectors___setitem__(self, *args)

    def pop(self):
        return _lizards.vectors_pop(self)

    def append(self, x):
        return _lizards.vectors_append(self, x)

    def empty(self):
        return _lizards.vectors_empty(self)

    def size(self):
        return _lizards.vectors_size(self)

    def swap(self, v):
        return _lizards.vectors_swap(self, v)

    def begin(self):
        return _lizards.vectors_begin(self)

    def end(self):
        return _lizards.vectors_end(self)

    def rbegin(self):
        return _lizards.vectors_rbegin(self)

    def rend(self):
        return _lizards.vectors_rend(self)

    def clear(self):
        return _lizards.vectors_clear(self)

    def get_allocator(self):
        return _lizards.vectors_get_allocator(self)

    def pop_back(self):
        return _lizards.vectors_pop_back(self)

    def erase(self, *args):
        return _lizards.vectors_erase(self, *args)

    def __init__(self, *args):
        _lizards.vectors_swiginit(self, _lizards.new_vectors(*args))

    def push_back(self, x):
        return _lizards.vectors_push_back(self, x)

    def front(self):
        return _lizards.vectors_front(self)

    def back(self):
        return _lizards.vectors_back(self)

    def assign(self, n, x):
        return _lizards.vectors_assign(self, n, x)

    def resize(self, *args):
        return _lizards.vectors_resize(self, *args)

    def insert(self, *args):
        return _lizards.vectors_insert(self, *args)

    def reserve(self, n):
        return _lizards.vectors_reserve(self, n)

    def capacity(self):
        return _lizards.vectors_capacity(self)
    __swig_destroy__ = _lizards.delete_vectors

# Register vectors in _lizards:
_lizards.vectors_swigregister(vectors)
class layouts_t(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    layouts = property(_lizards.layouts_t_layouts_get, _lizards.layouts_t_layouts_set)

    def __init__(self, arg2, arg3):
        _lizards.layouts_t_swiginit(self, _lizards.new_layouts_t(arg2, arg3))

    def layout(self, arg2):
        return _lizards.layouts_t_layout(self, arg2)

    def keys(self):
        return _lizards.layouts_t_keys(self)
    __swig_destroy__ = _lizards.delete_layouts_t

# Register layouts_t in _lizards:
_lizards.layouts_t_swigregister(layouts_t)
class template_t(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _lizards.template_t_swiginit(self, _lizards.new_template_t(*args))

    def cost(self):
        return _lizards.template_t_cost(self)

    def realize(self):
        return _lizards.template_t_realize(self)

    def save(self, arg2):
        return _lizards.template_t_save(self, arg2)

    def getactive(self):
        return _lizards.template_t_getactive(self)

    def setactive(self, arg2):
        return _lizards.template_t_setactive(self, arg2)
    __swig_destroy__ = _lizards.delete_template_t

# Register template_t in _lizards:
_lizards.template_t_swigregister(template_t)
class grid_t(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, arg2, arg3):
        _lizards.grid_t_swiginit(self, _lizards.new_grid_t(arg2, arg3))

    def lay_islands(self, arg2):
        return _lizards.grid_t_lay_islands(self, arg2)

    def generate_typical(self):
        return _lizards.grid_t_generate_typical(self)

    def __call__(self, arg2):
        return _lizards.grid_t___call__(self, arg2)
    width = property(_lizards.grid_t_width_get, _lizards.grid_t_width_set)
    height = property(_lizards.grid_t_height_get, _lizards.grid_t_height_set)

    def set(self, arg2, arg3, arg4):
        return _lizards.grid_t_set(self, arg2, arg3, arg4)

    def move(self, arg2, arg3):
        return _lizards.grid_t_move(self, arg2, arg3)

    def replace(self, arg2, arg3):
        return _lizards.grid_t_replace(self, arg2, arg3)

    def place_template(self, arg2, arg3, arg4, arg5):
        return _lizards.grid_t_place_template(self, arg2, arg3, arg4, arg5)

    def output(self, arg2):
        return _lizards.grid_t_output(self, arg2)

    def tostring(self):
        return _lizards.grid_t_tostring(self)

    def owned(self, arg2, arg3):
        return _lizards.grid_t_owned(self, arg2, arg3)

    def serialize(self):
        return _lizards.grid_t_serialize(self)
    __swig_destroy__ = _lizards.delete_grid_t

# Register grid_t in _lizards:
_lizards.grid_t_swigregister(grid_t)
class layout_m(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _lizards.layout_m_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _lizards.layout_m___nonzero__(self)

    def __bool__(self):
        return _lizards.layout_m___bool__(self)

    def __len__(self):
        return _lizards.layout_m___len__(self)
    def __iter__(self):
        return self.key_iterator()
    def iterkeys(self):
        return self.key_iterator()
    def itervalues(self):
        return self.value_iterator()
    def iteritems(self):
        return self.iterator()

    def __getitem__(self, key):
        return _lizards.layout_m___getitem__(self, key)

    def __delitem__(self, key):
        return _lizards.layout_m___delitem__(self, key)

    def has_key(self, key):
        return _lizards.layout_m_has_key(self, key)

    def keys(self):
        return _lizards.layout_m_keys(self)

    def values(self):
        return _lizards.layout_m_values(self)

    def items(self):
        return _lizards.layout_m_items(self)

    def __contains__(self, key):
        return _lizards.layout_m___contains__(self, key)

    def key_iterator(self):
        return _lizards.layout_m_key_iterator(self)

    def value_iterator(self):
        return _lizards.layout_m_value_iterator(self)

    def __setitem__(self, *args):
        return _lizards.layout_m___setitem__(self, *args)

    def asdict(self):
        return _lizards.layout_m_asdict(self)

    def __init__(self, *args):
        _lizards.layout_m_swiginit(self, _lizards.new_layout_m(*args))

    def empty(self):
        return _lizards.layout_m_empty(self)

    def size(self):
        return _lizards.layout_m_size(self)

    def swap(self, v):
        return _lizards.layout_m_swap(self, v)

    def begin(self):
        return _lizards.layout_m_begin(self)

    def end(self):
        return _lizards.layout_m_end(self)

    def rbegin(self):
        return _lizards.layout_m_rbegin(self)

    def rend(self):
        return _lizards.layout_m_rend(self)

    def clear(self):
        return _lizards.layout_m_clear(self)

    def get_allocator(self):
        return _lizards.layout_m_get_allocator(self)

    def count(self, x):
        return _lizards.layout_m_count(self, x)

    def erase(self, *args):
        return _lizards.layout_m_erase(self, *args)

    def find(self, x):
        return _lizards.layout_m_find(self, x)

    def lower_bound(self, x):
        return _lizards.layout_m_lower_bound(self, x)

    def upper_bound(self, x):
        return _lizards.layout_m_upper_bound(self, x)
    __swig_destroy__ = _lizards.delete_layout_m

# Register layout_m in _lizards:
_lizards.layout_m_swigregister(layout_m)
class hex_pv(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _lizards.hex_pv_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _lizards.hex_pv___nonzero__(self)

    def __bool__(self):
        return _lizards.hex_pv___bool__(self)

    def __len__(self):
        return _lizards.hex_pv___len__(self)

    def __getslice__(self, i, j):
        return _lizards.hex_pv___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _lizards.hex_pv___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _lizards.hex_pv___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _lizards.hex_pv___delitem__(self, *args)

    def __getitem__(self, *args):
        return _lizards.hex_pv___getitem__(self, *args)

    def __setitem__(self, *args):
        return _lizards.hex_pv___setitem__(self, *args)

    def pop(self):
        return _lizards.hex_pv_pop(self)

    def append(self, x):
        return _lizards.hex_pv_append(self, x)

    def empty(self):
        return _lizards.hex_pv_empty(self)

    def size(self):
        return _lizards.hex_pv_size(self)

    def swap(self, v):
        return _lizards.hex_pv_swap(self, v)

    def begin(self):
        return _lizards.hex_pv_begin(self)

    def end(self):
        return _lizards.hex_pv_end(self)

    def rbegin(self):
        return _lizards.hex_pv_rbegin(self)

    def rend(self):
        return _lizards.hex_pv_rend(self)

    def clear(self):
        return _lizards.hex_pv_clear(self)

    def get_allocator(self):
        return _lizards.hex_pv_get_allocator(self)

    def pop_back(self):
        return _lizards.hex_pv_pop_back(self)

    def erase(self, *args):
        return _lizards.hex_pv_erase(self, *args)

    def __init__(self, *args):
        _lizards.hex_pv_swiginit(self, _lizards.new_hex_pv(*args))

    def push_back(self, x):
        return _lizards.hex_pv_push_back(self, x)

    def front(self):
        return _lizards.hex_pv_front(self)

    def back(self):
        return _lizards.hex_pv_back(self)

    def assign(self, n, x):
        return _lizards.hex_pv_assign(self, n, x)

    def resize(self, *args):
        return _lizards.hex_pv_resize(self, *args)

    def insert(self, *args):
        return _lizards.hex_pv_insert(self, *args)

    def reserve(self, n):
        return _lizards.hex_pv_reserve(self, n)

    def capacity(self):
        return _lizards.hex_pv_capacity(self)
    __swig_destroy__ = _lizards.delete_hex_pv

# Register hex_pv in _lizards:
_lizards.hex_pv_swigregister(hex_pv)
class fpoint_v(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _lizards.fpoint_v_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _lizards.fpoint_v___nonzero__(self)

    def __bool__(self):
        return _lizards.fpoint_v___bool__(self)

    def __len__(self):
        return _lizards.fpoint_v___len__(self)

    def __getslice__(self, i, j):
        return _lizards.fpoint_v___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _lizards.fpoint_v___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _lizards.fpoint_v___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _lizards.fpoint_v___delitem__(self, *args)

    def __getitem__(self, *args):
        return _lizards.fpoint_v___getitem__(self, *args)

    def __setitem__(self, *args):
        return _lizards.fpoint_v___setitem__(self, *args)

    def pop(self):
        return _lizards.fpoint_v_pop(self)

    def append(self, x):
        return _lizards.fpoint_v_append(self, x)

    def empty(self):
        return _lizards.fpoint_v_empty(self)

    def size(self):
        return _lizards.fpoint_v_size(self)

    def swap(self, v):
        return _lizards.fpoint_v_swap(self, v)

    def begin(self):
        return _lizards.fpoint_v_begin(self)

    def end(self):
        return _lizards.fpoint_v_end(self)

    def rbegin(self):
        return _lizards.fpoint_v_rbegin(self)

    def rend(self):
        return _lizards.fpoint_v_rend(self)

    def clear(self):
        return _lizards.fpoint_v_clear(self)

    def get_allocator(self):
        return _lizards.fpoint_v_get_allocator(self)

    def pop_back(self):
        return _lizards.fpoint_v_pop_back(self)

    def erase(self, *args):
        return _lizards.fpoint_v_erase(self, *args)

    def __init__(self, *args):
        _lizards.fpoint_v_swiginit(self, _lizards.new_fpoint_v(*args))

    def push_back(self, x):
        return _lizards.fpoint_v_push_back(self, x)

    def front(self):
        return _lizards.fpoint_v_front(self)

    def back(self):
        return _lizards.fpoint_v_back(self)

    def assign(self, n, x):
        return _lizards.fpoint_v_assign(self, n, x)

    def resize(self, *args):
        return _lizards.fpoint_v_resize(self, *args)

    def insert(self, *args):
        return _lizards.fpoint_v_insert(self, *args)

    def reserve(self, n):
        return _lizards.fpoint_v_reserve(self, n)

    def capacity(self):
        return _lizards.fpoint_v_capacity(self)
    __swig_destroy__ = _lizards.delete_fpoint_v

# Register fpoint_v in _lizards:
_lizards.fpoint_v_swigregister(fpoint_v)
class point_v(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _lizards.point_v_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _lizards.point_v___nonzero__(self)

    def __bool__(self):
        return _lizards.point_v___bool__(self)

    def __len__(self):
        return _lizards.point_v___len__(self)

    def __getslice__(self, i, j):
        return _lizards.point_v___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _lizards.point_v___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _lizards.point_v___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _lizards.point_v___delitem__(self, *args)

    def __getitem__(self, *args):
        return _lizards.point_v___getitem__(self, *args)

    def __setitem__(self, *args):
        return _lizards.point_v___setitem__(self, *args)

    def pop(self):
        return _lizards.point_v_pop(self)

    def append(self, x):
        return _lizards.point_v_append(self, x)

    def empty(self):
        return _lizards.point_v_empty(self)

    def size(self):
        return _lizards.point_v_size(self)

    def swap(self, v):
        return _lizards.point_v_swap(self, v)

    def begin(self):
        return _lizards.point_v_begin(self)

    def end(self):
        return _lizards.point_v_end(self)

    def rbegin(self):
        return _lizards.point_v_rbegin(self)

    def rend(self):
        return _lizards.point_v_rend(self)

    def clear(self):
        return _lizards.point_v_clear(self)

    def get_allocator(self):
        return _lizards.point_v_get_allocator(self)

    def pop_back(self):
        return _lizards.point_v_pop_back(self)

    def erase(self, *args):
        return _lizards.point_v_erase(self, *args)

    def __init__(self, *args):
        _lizards.point_v_swiginit(self, _lizards.new_point_v(*args))

    def push_back(self, x):
        return _lizards.point_v_push_back(self, x)

    def front(self):
        return _lizards.point_v_front(self)

    def back(self):
        return _lizards.point_v_back(self)

    def assign(self, n, x):
        return _lizards.point_v_assign(self, n, x)

    def resize(self, *args):
        return _lizards.point_v_resize(self, *args)

    def insert(self, *args):
        return _lizards.point_v_insert(self, *args)

    def reserve(self, n):
        return _lizards.point_v_reserve(self, n)

    def capacity(self):
        return _lizards.point_v_capacity(self)
    __swig_destroy__ = _lizards.delete_point_v

# Register point_v in _lizards:
_lizards.point_v_swigregister(point_v)
class single_v(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _lizards.single_v_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _lizards.single_v___nonzero__(self)

    def __bool__(self):
        return _lizards.single_v___bool__(self)

    def __len__(self):
        return _lizards.single_v___len__(self)

    def __getslice__(self, i, j):
        return _lizards.single_v___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _lizards.single_v___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _lizards.single_v___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _lizards.single_v___delitem__(self, *args)

    def __getitem__(self, *args):
        return _lizards.single_v___getitem__(self, *args)

    def __setitem__(self, *args):
        return _lizards.single_v___setitem__(self, *args)

    def pop(self):
        return _lizards.single_v_pop(self)

    def append(self, x):
        return _lizards.single_v_append(self, x)

    def empty(self):
        return _lizards.single_v_empty(self)

    def size(self):
        return _lizards.single_v_size(self)

    def swap(self, v):
        return _lizards.single_v_swap(self, v)

    def begin(self):
        return _lizards.single_v_begin(self)

    def end(self):
        return _lizards.single_v_end(self)

    def rbegin(self):
        return _lizards.single_v_rbegin(self)

    def rend(self):
        return _lizards.single_v_rend(self)

    def clear(self):
        return _lizards.single_v_clear(self)

    def get_allocator(self):
        return _lizards.single_v_get_allocator(self)

    def pop_back(self):
        return _lizards.single_v_pop_back(self)

    def erase(self, *args):
        return _lizards.single_v_erase(self, *args)

    def __init__(self, *args):
        _lizards.single_v_swiginit(self, _lizards.new_single_v(*args))

    def push_back(self, x):
        return _lizards.single_v_push_back(self, x)

    def front(self):
        return _lizards.single_v_front(self)

    def back(self):
        return _lizards.single_v_back(self)

    def assign(self, n, x):
        return _lizards.single_v_assign(self, n, x)

    def resize(self, *args):
        return _lizards.single_v_resize(self, *args)

    def insert(self, *args):
        return _lizards.single_v_insert(self, *args)

    def reserve(self, n):
        return _lizards.single_v_reserve(self, n)

    def capacity(self):
        return _lizards.single_v_capacity(self)
    __swig_destroy__ = _lizards.delete_single_v

# Register single_v in _lizards:
_lizards.single_v_swigregister(single_v)
class player_v(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _lizards.player_v_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _lizards.player_v___nonzero__(self)

    def __bool__(self):
        return _lizards.player_v___bool__(self)

    def __len__(self):
        return _lizards.player_v___len__(self)

    def __getslice__(self, i, j):
        return _lizards.player_v___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _lizards.player_v___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _lizards.player_v___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _lizards.player_v___delitem__(self, *args)

    def __getitem__(self, *args):
        return _lizards.player_v___getitem__(self, *args)

    def __setitem__(self, *args):
        return _lizards.player_v___setitem__(self, *args)

    def pop(self):
        return _lizards.player_v_pop(self)

    def append(self, x):
        return _lizards.player_v_append(self, x)

    def empty(self):
        return _lizards.player_v_empty(self)

    def size(self):
        return _lizards.player_v_size(self)

    def swap(self, v):
        return _lizards.player_v_swap(self, v)

    def begin(self):
        return _lizards.player_v_begin(self)

    def end(self):
        return _lizards.player_v_end(self)

    def rbegin(self):
        return _lizards.player_v_rbegin(self)

    def rend(self):
        return _lizards.player_v_rend(self)

    def clear(self):
        return _lizards.player_v_clear(self)

    def get_allocator(self):
        return _lizards.player_v_get_allocator(self)

    def pop_back(self):
        return _lizards.player_v_pop_back(self)

    def erase(self, *args):
        return _lizards.player_v_erase(self, *args)

    def __init__(self, *args):
        _lizards.player_v_swiginit(self, _lizards.new_player_v(*args))

    def push_back(self, x):
        return _lizards.player_v_push_back(self, x)

    def front(self):
        return _lizards.player_v_front(self)

    def back(self):
        return _lizards.player_v_back(self)

    def assign(self, n, x):
        return _lizards.player_v_assign(self, n, x)

    def resize(self, *args):
        return _lizards.player_v_resize(self, *args)

    def insert(self, *args):
        return _lizards.player_v_insert(self, *args)

    def reserve(self, n):
        return _lizards.player_v_reserve(self, n)

    def capacity(self):
        return _lizards.player_v_capacity(self)
    __swig_destroy__ = _lizards.delete_player_v

# Register player_v in _lizards:
_lizards.player_v_swigregister(player_v)
class double_m(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _lizards.double_m_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _lizards.double_m___nonzero__(self)

    def __bool__(self):
        return _lizards.double_m___bool__(self)

    def __len__(self):
        return _lizards.double_m___len__(self)
    def __iter__(self):
        return self.key_iterator()
    def iterkeys(self):
        return self.key_iterator()
    def itervalues(self):
        return self.value_iterator()
    def iteritems(self):
        return self.iterator()

    def __getitem__(self, key):
        return _lizards.double_m___getitem__(self, key)

    def __delitem__(self, key):
        return _lizards.double_m___delitem__(self, key)

    def has_key(self, key):
        return _lizards.double_m_has_key(self, key)

    def keys(self):
        return _lizards.double_m_keys(self)

    def values(self):
        return _lizards.double_m_values(self)

    def items(self):
        return _lizards.double_m_items(self)

    def __contains__(self, key):
        return _lizards.double_m___contains__(self, key)

    def key_iterator(self):
        return _lizards.double_m_key_iterator(self)

    def value_iterator(self):
        return _lizards.double_m_value_iterator(self)

    def __setitem__(self, *args):
        return _lizards.double_m___setitem__(self, *args)

    def asdict(self):
        return _lizards.double_m_asdict(self)

    def __init__(self, *args):
        _lizards.double_m_swiginit(self, _lizards.new_double_m(*args))

    def empty(self):
        return _lizards.double_m_empty(self)

    def size(self):
        return _lizards.double_m_size(self)

    def swap(self, v):
        return _lizards.double_m_swap(self, v)

    def begin(self):
        return _lizards.double_m_begin(self)

    def end(self):
        return _lizards.double_m_end(self)

    def rbegin(self):
        return _lizards.double_m_rbegin(self)

    def rend(self):
        return _lizards.double_m_rend(self)

    def clear(self):
        return _lizards.double_m_clear(self)

    def get_allocator(self):
        return _lizards.double_m_get_allocator(self)

    def count(self, x):
        return _lizards.double_m_count(self, x)

    def erase(self, *args):
        return _lizards.double_m_erase(self, *args)

    def find(self, x):
        return _lizards.double_m_find(self, x)

    def lower_bound(self, x):
        return _lizards.double_m_lower_bound(self, x)

    def upper_bound(self, x):
        return _lizards.double_m_upper_bound(self, x)

    def __setitem(self, s, d):
        return _lizards.double_m___setitem(self, s, d)

    def __getitem(self, s):
        return _lizards.double_m___getitem(self, s)
    __swig_destroy__ = _lizards.delete_double_m

# Register double_m in _lizards:
_lizards.double_m_swigregister(double_m)
class rgb_m(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _lizards.rgb_m_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _lizards.rgb_m___nonzero__(self)

    def __bool__(self):
        return _lizards.rgb_m___bool__(self)

    def __len__(self):
        return _lizards.rgb_m___len__(self)
    def __iter__(self):
        return self.key_iterator()
    def iterkeys(self):
        return self.key_iterator()
    def itervalues(self):
        return self.value_iterator()
    def iteritems(self):
        return self.iterator()

    def __getitem__(self, key):
        return _lizards.rgb_m___getitem__(self, key)

    def __delitem__(self, key):
        return _lizards.rgb_m___delitem__(self, key)

    def has_key(self, key):
        return _lizards.rgb_m_has_key(self, key)

    def keys(self):
        return _lizards.rgb_m_keys(self)

    def values(self):
        return _lizards.rgb_m_values(self)

    def items(self):
        return _lizards.rgb_m_items(self)

    def __contains__(self, key):
        return _lizards.rgb_m___contains__(self, key)

    def key_iterator(self):
        return _lizards.rgb_m_key_iterator(self)

    def value_iterator(self):
        return _lizards.rgb_m_value_iterator(self)

    def __setitem__(self, *args):
        return _lizards.rgb_m___setitem__(self, *args)

    def asdict(self):
        return _lizards.rgb_m_asdict(self)

    def __init__(self, *args):
        _lizards.rgb_m_swiginit(self, _lizards.new_rgb_m(*args))

    def empty(self):
        return _lizards.rgb_m_empty(self)

    def size(self):
        return _lizards.rgb_m_size(self)

    def swap(self, v):
        return _lizards.rgb_m_swap(self, v)

    def begin(self):
        return _lizards.rgb_m_begin(self)

    def end(self):
        return _lizards.rgb_m_end(self)

    def rbegin(self):
        return _lizards.rgb_m_rbegin(self)

    def rend(self):
        return _lizards.rgb_m_rend(self)

    def clear(self):
        return _lizards.rgb_m_clear(self)

    def get_allocator(self):
        return _lizards.rgb_m_get_allocator(self)

    def count(self, x):
        return _lizards.rgb_m_count(self, x)

    def erase(self, *args):
        return _lizards.rgb_m_erase(self, *args)

    def find(self, x):
        return _lizards.rgb_m_find(self, x)

    def lower_bound(self, x):
        return _lizards.rgb_m_lower_bound(self, x)

    def upper_bound(self, x):
        return _lizards.rgb_m_upper_bound(self, x)
    __swig_destroy__ = _lizards.delete_rgb_m

# Register rgb_m in _lizards:
_lizards.rgb_m_swigregister(rgb_m)
class single_t(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    id = property(_lizards.single_t_id_get, _lizards.single_t_id_set)
    file = property(_lizards.single_t_file_get, _lizards.single_t_file_set)
    center = property(_lizards.single_t_center_get, _lizards.single_t_center_set)
    bounds = property(_lizards.single_t_bounds_get, _lizards.single_t_bounds_set)
    path = property(_lizards.single_t_path_get, _lizards.single_t_path_set)

    def __init__(self):
        _lizards.single_t_swiginit(self, _lizards.new_single_t())
    __swig_destroy__ = _lizards.delete_single_t

# Register single_t in _lizards:
_lizards.single_t_swigregister(single_t)
class singles_t(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    bounds = property(_lizards.singles_t_bounds_get, _lizards.singles_t_bounds_set)
    singles = property(_lizards.singles_t_singles_get, _lizards.singles_t_singles_set)

    def size(self):
        return _lizards.singles_t_size(self)

    def __init__(self):
        _lizards.singles_t_swiginit(self, _lizards.new_singles_t())
    __swig_destroy__ = _lizards.delete_singles_t

# Register singles_t in _lizards:
_lizards.singles_t_swigregister(singles_t)
class rgb_t(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    red = property(_lizards.rgb_t_red_get, _lizards.rgb_t_red_set)
    green = property(_lizards.rgb_t_green_get, _lizards.rgb_t_green_set)
    blue = property(_lizards.rgb_t_blue_get, _lizards.rgb_t_blue_set)

    def __init__(self):
        _lizards.rgb_t_swiginit(self, _lizards.new_rgb_t())
    __swig_destroy__ = _lizards.delete_rgb_t

# Register rgb_t in _lizards:
_lizards.rgb_t_swigregister(rgb_t)
class output_t(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    colours = property(_lizards.output_t_colours_get, _lizards.output_t_colours_set)
    dimensions = property(_lizards.output_t_dimensions_get, _lizards.output_t_dimensions_set)

    def __init__(self, *args):
        _lizards.output_t_swiginit(self, _lizards.new_output_t(*args))

    def set_colour(self, arg2, arg3, arg4, arg5):
        return _lizards.output_t_set_colour(self, arg2, arg3, arg4, arg5)

    def json(self, arg2):
        return _lizards.output_t_json(self, arg2)

    def svg(self, arg2):
        return _lizards.output_t_svg(self, arg2)
    __swig_destroy__ = _lizards.delete_output_t

# Register output_t in _lizards:
_lizards.output_t_swigregister(output_t)
class player_t(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    startup = property(_lizards.player_t_startup_get, _lizards.player_t_startup_set)
    clan = property(_lizards.player_t_clan_get, _lizards.player_t_clan_set)
    code = property(_lizards.player_t_code_get, _lizards.player_t_code_set)

    def __init__(self):
        _lizards.player_t_swiginit(self, _lizards.new_player_t())
    __swig_destroy__ = _lizards.delete_player_t

# Register player_t in _lizards:
_lizards.player_t_swigregister(player_t)
class game_t(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    grid = property(_lizards.game_t_grid_get, _lizards.game_t_grid_set)
    nplayers = property(_lizards.game_t_nplayers_get, _lizards.game_t_nplayers_set)
    players = property(_lizards.game_t_players_get, _lizards.game_t_players_set)

    def report(self):
        return _lizards.game_t_report(self)

    def tostring(self):
        return _lizards.game_t_tostring(self)

    def __init__(self, arg2, arg3):
        _lizards.game_t_swiginit(self, _lizards.new_game_t(arg2, arg3))

    def player(self, i):
        return _lizards.game_t_player(self, i)

    def bootstrap(self):
        return _lizards.game_t_bootstrap(self)
    __swig_destroy__ = _lizards.delete_game_t

# Register game_t in _lizards:
_lizards.game_t_swigregister(game_t)
class view_t(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, arg2, arg3):
        _lizards.view_t_swiginit(self, _lizards.new_view_t(arg2, arg3))
    __swig_destroy__ = _lizards.delete_view_t

# Register view_t in _lizards:
_lizards.view_t_swigregister(view_t)
class serial_t(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _lizards.serial_t_swiginit(self, _lizards.new_serial_t())

    def to_file(self, arg2):
        return _lizards.serial_t_to_file(self, arg2)

    @staticmethod
    def from_file(arg1):
        return _lizards.serial_t_from_file(arg1)
    __swig_destroy__ = _lizards.delete_serial_t

# Register serial_t in _lizards:
_lizards.serial_t_swigregister(serial_t)

