{
    "layout":3,
    "home":"06",
    "hexes":[
	{"id":"01","type":"PEA","band":{"GRY":50}},
	{"id":"02","type":"FER"},
	{"id":"03","type":"SCR","band":{"GRN":50}},
	{"id":"04","type":"SCR"},
	{"id":"05","type":"SCR","band":{"RED":100, "GRN":10}},
	{"id":"06","type":"RED","pop":60},
	{"id":"07","type":"FER","band":{"RED":100, "YEL": 50}},
	{"id":"08","type":"SCR"},
	{"id":"09","type":"FER"},
	{"id":"10","type":"SCR","band":{"GRN":10}},
	{"id":"11","type":"PEA","band":{"RED":100, "GRY":50}}
    ]
}
