{
    "layout": 8,
    "home": "10",
    "hexes": [
	{"id":"01","type":"PEA"},
	{"id":"02","type":"SCR"},
	{"id":"03","type":"TEM"},
	{"id":"04","type":"SCR"},
	{"id":"05","type":"RED", "band":{"RED":10}},
	{"id":"06","type":"SCR", "band":{"GRN":10}},
	{"id":"07","type":"PEA"},
	{"id":"08","type":"SCR", "band":{"GRN":10}},
	{"id":"09","type":"FER"},
	{"id":"10","type":"GRY", "band":{"RED":10}},
	{"id":"11","type":"SCR"},
	{"id":"12","type":"RED", "band":{"RED":70}},
	{"id":"13","type":"FER"},
	{"id":"14","type":"SCR", "band":{"GRN":10}},
	{"id":"15","type":"RUI", "band":{"GRY":50}},
	{"id":"16","type":"SCR"},
	{"id":"17","type":"RUI"},
	{"id":"18","type":"SCR"},
	{"id":"19","type":"SWA"},
	{"id":"20","type":"SCR"},
	{"id":"21","type":"SCR"},
	{"id":"22","type":"RUI"}
    ]
}
