{
    "layout":1,
    "home":"07",
    "hexes":[
	{"id":"01","type":"TEM","band":{"RED":90}},
	{"id":"02","type":"RUI","band":{"GRN":10,"GRY":50,"YEL":10,"BLK":10}},
	{"id":"03","type":"RUI","band":{"GRN":10,"GRY":50,"YEL":10,"BLK":10}},
	{"id":"04","type":"FER"},
	{"id":"05","type":"FER","band":{"RED":10}},
	{"id":"06","type":"SWA","band":{"GRN":10}},
	{"id":"07","type":"YEL","pop":20, "band":{"RED":80, "YEL":10, "BLK":50}},
    ]
}
