CC	= gcc
CXX	= g++ 

GTK_CFLAGS	= @GTK_CFLAGS@
GTK_LIBS	= @GTK_LIBS@

GLIB_CFLAGS	= -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sysprof-6
GLIB_LIBS	= -lglib-2.0

RSVG_CFLAGS	= -pthread -I/usr/include/librsvg-2.0 -I/usr/include/cairo -I/usr/include/libxml2 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/webp -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sysprof-6 -I/usr/include/cairo -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/pixman-1
RSVG_LIBS	= -lrsvg-2 -lgio-2.0 -lgdk_pixbuf-2.0 -lgobject-2.0 -lglib-2.0 -lcairo

CAIROMM_CFLAGS	= -I/usr/include/cairomm-1.16 -I/usr/lib64/cairomm-1.16/include -I/usr/include/sigc++-3.0 -I/usr/lib64/sigc++-3.0/include -I/usr/include/cairo -I/usr/include/freetype2 -I/usr/include/pixman-1 -I/usr/include/libpng16
CAIROMM_LIBS	= -lcairomm-1.16 -lsigc-3.0 -lcairo -lpng16

JSON_CFLAGS	= -I/usr/include/json-c
JSON_LIBS	= -ljson-c
