void show_title (void);
void get_switch_list (World *);
void put_switch_list(World *);
void get_home_den_status (World *);
void put_home_den_status (World *);
void get_player_list (World *);
void save_player_list (World *);
void get_spy_list (World *);
void put_spy_list (World *);
void get_world (World *);
void put_world (World *);
void OpenPlayerFiles(World *);
void ClosePlayerFiles(World *);
