#!/bin/sh

RESOLUTION=400
REDUCTION=4

if [ $# -eq 0 ];
then
	echo "$0: <filename>"
	exit 0
fi

if [ -f $1.ps ];
then
	FILE=$1
else
	FILE=`echo $1 | sed 's/.ps//'`;
fi

if [ ! -r ${FILE}.ps ];
then
	echo "$FILE.ps does not seem to be readable.";
	exit 1
fi

# find . -name "$FILE-[0-9]*.png" -exec rm \{\} \;

gs -sDEVICE=png256 -sOutputFile=/tmp/$FILE-%d.png \
-r${RESOLUTION} -dBATCH -dNOPAUSE -sPAPERSIZE=a4 $FILE.ps

for i in /tmp/$FILE*.png
do
	mv $i $i.$$
	pngtopnm $i.$$ | pnmscale -reduce $REDUCTION | pnmtopng > $i && rm $i.$$
done
